apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobookstoreapi
spec:
  selector:
    matchLabels:
      app: gobookstoreapi
  replicas: 2
  template:
    metadata:
      labels:
        app: gobookstoreapi
    spec:
      containers:
        - name: my-app
          image: sami7786/gobookstoreapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gobookstoreapi-service
spec:
  selector:
    app: gobookstoreapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000