---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobookstoreapi
spec:
  selector:
    matchLabels:
      app: gobookstoreapi
  replicas: 2
  template:
    metadata:
      labels:
        app: gobookstoreapi
    spec:
      containers:
        - name: gobookstoreapi-app
          image: sami7786/gobookstoreapi:jaeger
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: jaeger-collector.observability.svc:4318
            - name: adminusername
              value: admin
            - name: adminpassword
              value: admin
            - name: jwtsecret
              value: orangeCat
---
apiVersion: v1
kind: Service
metadata:
  name: gobookstoreapi-service
spec:
  selector:
    app: gobookstoreapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
