---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gobookstoreapi.serviceName }}
  namespace: {{ .Values.gobookstoreapi.namespace }}
  labels:
    app: {{ .Values.gobookstoreapi.appName }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.gobookstoreapi.ports.containerPort }}"
spec:
  selector:
    app: {{ .Values.gobookstoreapi.appName }}
  type: {{ .Values.gobookstoreapi.specType }}
  ports:
    - protocol: {{ .Values.gobookstoreapi.ports.protocol }}
      port:  {{ .Values.gobookstoreapi.ports.containerPort }}
      targetPort: {{ .Values.gobookstoreapi.ports.targetPort }}
      nodePort: {{ .Values.gobookstoreapi.ports.nodePort }}
