apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.name}}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          env:
            - name: adminusername
              valueFrom:
                secretKeyRef:
                  key: adminusername
                  name: {{ .Values.secret.name}}
            - name: adminpassword
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: {{ .Values.secret.name}}
            - name: jwtsecret
              valueFrom:
                secretKeyRef:
                  key: jwtsecret
                  name: {{ .Values.secret.name}}

