---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.perses.appName }}
  namespace: {{ .Values.perses.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.perses.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.perses.appName }}
    spec:
      containers:
        - name: {{ .Values.perses.appName }}
          image: "{{ .Values.perses.image.name }}:{{ .Values.perses.image.tag }}"
          args:
            - "--config=/etc/perses/config.yaml"
          ports:
            - containerPort: {{ .Values.perses.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/perses
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.perses.appName }}-config


