apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.perses.appName }}-config
  namespace: {{ .Values.perses.namespace }}
data:
  config.yaml: |
    datasources:
      - name: prometheus
        type: prometheus
        default: true
        url: {{ .Values.perses.prometheusURL }}
