---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.perses.appName }}-service
  namespace: {{ .Values.perses.namespace }}
spec:
  type: {{ .Values.perses.serviceSpecType }}
  ports:
    - port: 80
      targetPort: {{ .Values.perses.containerPort }}
      nodePort: 30030
  selector:
    app: {{ .Values.perses.appName }}
