apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gobookstoreapi.secret.name }}
  labels:
    type: env-secret
data:
  adminusername: {{ .Values.gobookstoreapi.secret.data.adminusername | b64enc }}
  adminpassword: {{ .Values.gobookstoreapi.secret.data.adminpassword | b64enc }}
  jwtsecret: {{ .Values.gobookstoreapi.secret.data.jwtsecret | b64enc }}
