apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    type: env-secret
data:
  adminUsername: {{ .Values.secret.data.adminUsername | b64enc }}
  adminPassword: {{ .Values.secret.data.adminPassword | b64enc }}