apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.specType }}
  ports:
    - protocol: {{ .Values.ports.protocol }}
      port:  {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.targetPort }}
      nodePort: {{ .Values.ports.nodePort }}