apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  namespace: default
  name: gobookstoreapi
spec:
  endpoints:
    - interval: 10s
  selector:
    matchLabels:
      app: gobookstoreapi