apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  labels:
    perses.dev/resource: "true"
    perses.dev/type: "Datasource"
data:
  prometheus.yaml: |
    kind: Datasource
    metadata:
      name: prometheus
      project: default
    spec:
      default: true
      plugin:
        kind: PrometheusDatasource
        spec:
          directUrl: http://gobookstoreapi-prometheus-server.default.svc.cluster.local

